# This integration test is unfinished.
# The dream would be to ru the test suite after the tf apply
# but it's fairly flaky still.

name: Run hari server integration tests on k8s (kind)
on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 00 * * *'

jobs:

  test:
    name: Hari server integration tests
    runs-on: ubuntu-latest
    steps:
    - name: Set the environment variable  
      run: |
        echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Kind
      uses: engineerd/setup-kind@v0.3.0

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: agus7fauzi/xinhari
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Apply tf files
      run: |
        bash scripts/launch-kind.sh

    - name: Apply failed, show platform logs
      if: ${{ failure() }}
      run: |
        kubectl get pods -n platform | awk '{print $1}' | xargs -n1 kubectl logs -n platform


